# profile: Default lightweight nfqws2

--uid=0:0
--qnum=200
--bind-fix4
--bind-fix6
--lua-init=@/data/adb/modules/nzapret/lua/zapret-lib.lua
--lua-init=@/data/adb/modules/nzapret/lua/zapret-antidpi.lua
--blob=tls_google:@/data/adb/modules/nzapret/payloads/tls_clienthello_www_google_com.bin
--blob=quic_google:@/data/adb/modules/nzapret/payloads/quic_initial_www_google_com.bin
--filter-tcp=80
--filter-l7=http
--hostlist=/data/adb/modules/nzapret/lists/list-general.txt
--hostlist=/data/adb/modules/nzapret/lists/list-google.txt
--hostlist=/data/adb/modules/nzapret/lists/list-user.txt
--out-range=-d5
--payload=http_req
--lua-desync=fake:blob=fake_default_http:tcp_ts=-100:repeats=1
--lua-desync=multisplit:seqovl=1:pos=1
--new
--filter-tcp=443
--filter-l7=tls
--hostlist=/data/adb/modules/nzapret/lists/list-general.txt
--hostlist=/data/adb/modules/nzapret/lists/list-google.txt
--hostlist=/data/adb/modules/nzapret/lists/list-user.txt
--out-range=-d5
--payload=tls_client_hello
--lua-desync=fake:blob=tls_google:tcp_ts=-100:repeats=1
--lua-desync=multisplit:seqovl=1:pos=1
--new
--filter-udp=443
--filter-l7=quic
--hostlist=/data/adb/modules/nzapret/lists/list-google.txt
--hostlist=/data/adb/modules/nzapret/lists/list-user.txt
--out-range=-d5
--payload=quic_initial
--lua-desync=fake:blob=quic_google:repeats=1
--lua-desync=send:ipfrag:ipfrag_pos_udp=8
